# Generated by Django 3.2.8 on 2021-10-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0023_auto_20211016_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='wdf_test_person', serialize=False, to='cms.cmsplugin')),
                ('firstname', models.CharField(default='Name', max_length=200)),
                ('surname', models.CharField(default='Surname', max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
